### PR TITLE
page 11

### PR DESCRIPTION
**Pull request by jzatarski**
I have completed page 11. I have used the whitespace format which I think is correct (that I have detailed in #8)
that is:

```
<SPx5>AAAA DD DD DD<TAB><rest of line here>
```

On lines which did not include the data section, I used

```
<SPx5>AAAA<SPx9><TAB><rest of line here>
```

On lines which lacked even the address, I used:

```
<SPx18><TAB><rest of line here>
```

In these cases, I could have used tabs in place of the spaces, but I chose not to. I am not sure if this is 'correct' or not. I suppose the 'correct' method would be to duplicate the raw characters that the assembler atari used produced in the listing file. However, short of getting our hands on some DEC PDP or DEC VAX equipment (not too hard, I know some people) AND getting the same assembler Atari used (much harder, possibly impossible), we won't ever really know for sure what was output exactly in these cases.

### CODE REVIEW

**Comment by XioNYC** [comment]
I eyeballed the rest of the listing before moving onto page 12.  Probably the reason for all the confusion is that the OS equates and charset data (pages 1-13) aren't as clear-cut.  Most of the actual code (pages 13-109) follows a "AAAA BB CC DD<TAB>Label<TAB>Code" format, so that's what I'm sticking to.

Even though they're generated by the assembler, I want to retain the addresses/opcode blocks ("AAAA BB CC DD").  These could easily be stripped off and replace with sequential line numbers if we wanted to compile the sources.  Then again, the odds of getting a PDP/VAX _and_ the assembler that Atari used is pretty unlikely.

<!> ADDENDUM: Your page 11 is on target; we can forgo the five space characters at the start of every line and start with the address ("AAAA").

**Comment by jzatarski** [comment]
I have added another page, number 13.

**Comment by XioNYC** [comment]
(I'm having a bit of trouble resolving a branch conflict)

**Comment by jzatarski** [comment]
what conflict are you trying to resolve? this one? I'm going to close this pull request, as it's no longer needed. It seems page 11 and 13 have been added by other means, so no need to merge.

**Comment by XioNYC** [comment]
I don't know, actually - all I saw was some message saying something to the effect of "please remove page 11/13 because they're in conflict" or somesuch...
- sigh \*  Version control was so much easier back in the days of LIST "C:

Thanks, jzatarski.

**Pull request closed without merging**
