### PR TITLE
Let's carve up page ranges.

### PR DESCRIPTION
**Pull request by edburns**
We can update the table as more people chip in.

### CODE REVIEW

**Comment by XioNYC** [comment]
Good idea - I'll split the text file into representations of [physical] pages

**Comment by XioNYC** [comment]
I've (sort of*) described the "page claim" system in 000.txt: upload a blank file representing the page you plan to type in, and type it in.  It's more versatile than splitting the work in half, and it's more amenable to the "I'll chip in a page or two"-variety of contributor.

(\* It's been a long post-midnight slog so I might not have worded it elegantly)

**Comment by jzatarski** [comment]
can I get permission to add pages to the repository? or do you want us to do this through pull requests?

**Comment by XioNYC** [comment]
I'm sorry - it took me too long to figure out how to do that :-P I'm new to GitHub's ways... :-D

**Comment by savetz** [comment]
Oh, another comment there:

"The problem with the AtariMuseum listing is that it's not actually the source but is the output from an assembly run.

But I should think with the combined resources that are available a properly commented and working source could be created."

**Comment by savetz** [comment]
Did my previous comment show up here? I'm lame at github.

Curt Vendel shared this on the AtariAge forum:
https://www.dropbox.com/s/kem927vs9nea4dx/RAIDERS.TXT?dl=0

He said it's the source. But someone else complained that lines are truncated, and the other guy says it's an output from an assembly run.

I leave it to you experts :)

**Comment by XioNYC** [comment]
Me? Expert?? Don't look at me - I'm a stranger to Github myself!

Curt's RAIDERS.TXT looks more like an OCRed book containing source code.  It is helpful for distinguishing B/8, D/O/0, G/C/Q, and the like in variable names, but it isn't the stuff that the printout is made of.  It is indeed truncated and in a very different syntax vis-a-vis the hardcopy.

From what little assembly I do know\* it looks like both versions are output from assembly runs: there are no line numbers present, only addresses and bytecodes.  jzatarski and I presumed it was a PDP using an assembler known only to Atari and History (and History isn't saying much), but the the mnemonics and syntax of the hardcopy is consistent with Atari Assembler Editor.  I wouldn't be surprised if replacing the addresses and bytecodes with sequential line numbers resulted in assembleable code... but I get ahead of myself: the first priority is getting everything typed in; pretty-printing and assembly come later.

(\* Mostly from an Antic opcode chart, some [decimal] Compute! MLX/DATA dumps, and http://atariwiki.strotmann.de/wiki/Wiki.jsp?page=Atari%20Assembler%20Editor )

**Comment by jzatarski** [comment]
yes, I think the source provided by curt was assembled using atari CAMAC, which seems to be an in house developed assembler that ran on a Data General MV/8000. The version we have, was built with Microtec's 6500 series cross assembler. I'm not sure what that one ran on, but I think this because I have some 800 OS source that states it was 'converted' to be compiled by the Microtec compiler. That source has a very similar format to the formatting of the listing we are working on. It includes things like the .PAGE directives which I mentioned when responding to the blank pages issue. Perhaps Curt can uncover something about this. I think it would be interesting to produce the original source file from the listing(s) we have as accurately as we can, but for now we should just focus on converting the listing to text.

I think the likeness of the syntax between Atari's Assembler Editor and this, are likely due to the programmer of Assembler Editor using an assembler at atari, and duplicating the syntax somewhat, as it was what he knew and was familiar with.

**Pull request merged**
